### ISSUE TITLE
[PE-D] Outdated documentation in UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-T10-3/tp#265] opened 2021-10-30 19:05 UTC
![image.png](https://raw.githubusercontent.com/jyxhazcake/ped/main/files/15917c4f-2969-4866-b51b-bb80242ce972.png)

Commands in this image are outdated.

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: jyxhazcake/ped#3

**Comment by arraysius** [comment] 2021-11-01 08:22
Duplicate of #268

**Closed** 2021-11-01 08:33 UTC
Labels: type.Bug, ped.Duplicate
